<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '(not use)' => '',
    '* Resize table columns just like a spreadsheet by dragging the column edges.' => '',
    'All' => '',
    'Are you sure want to delete this item' => '',
    'Are you sure?' => '',
    'Assignment' => '',
    'Cancel' => '',
    'Class Name' => '',
    'Close' => '',
    'Create More' => '',
    'Create new rule' => '',
    'Create new {0}' => '',
    'Data' => '',
    'Delete' => '',
    'Description' => '',
    'Edit' => '',
    'Have been create new {0} success' => '',
    'ID' => '',
    'Name' => '',
    'Ok' => '',
    'Page' => '',
    'Permission name' => '',
    'Permissions' => '',
    'Permisstions Manager' => '',
    'Reload Grid' => '',
    'Role name' => '',
    'Roles' => '',
    'Roles Manager' => '',
    'Rule Name' => '',
    'Rule not exists' => '',
    'Rules Manager' => '',
    'Save' => '',
    'Show all data' => '',
    'Show first page data' => '',
    'The requested page does not exist.' => '',
    'Update' => '',
    'Update {0}' => '',
    'User Assignment' => '',
    'User ID' => '',
    'View' => '',
];
